### PR TITLE
Update repo name when processing issue/PR webhooks

### LINKED ISSUE #292: GitHub interface: replace repo_name with repo_id
*Type*: Bug

### Description
When a GitHub repo is renamed, no notification is delivered via OpenBounty GitHub App webhook. So an old repo name is being stored in the database, which is not good, as it is used for some aspects of the functionality, like QR code generation, repo fetching from DB, etc.

### Solution
Replace all usage of `repo_name` in code when it is used as a repo identifier with references to `repo_id`, which is immutable. Perhaps it makes sense to check `repo_name` field in each GH webhook delivery and update the DB value if changed, so that the UI reflects name changes.

### PR DESCRIPTION
**Pull request by siphiuel**
Fixes #292 

Repo name is updated if necessary each time issue/PR webhook payload is processed.

Also, some unused code was removed, and `update-repo-generic` query was replaced with more specific `update-repo-state` query.

**Status**: Finished.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Please don't get blocked on me being back to review this. So feel free to move this to testing if you think it gets the job done ☺️

**Comment by churik** [comment]
## 1. After deleting GH repo bounties are still displayed on SOB list

Steps:
*Requirements*: GH account is whitelisted, signed app, test application is added to repo;
- create issue 
- add `bounty` label
- open https://testing.openbounty.status.im/app
- wait until new bounty will be displayed in 'Open bounties' list
- delete repo
- open https://testing.openbounty.status.im/app

### Actual result:
no bounties from deleted repo is shown

### Expected result: 
bounties from deleted repo are still in 'Open bounties' list

**Video:** http://take.ms/Sb8jH
**OS:**  Mac OS High Sierra
**Browser:** Chrome 64

@siphiuel if you think that it should be moved in separate issue - just let me know, repo renaming actually works.

**Comment by siphiuel** [comment]
@churik I suggest creating a separate issue. Repo `close` events go via a different webhook.

**Comment by churik** [comment]
Moved to separate issue: #356

**Comment by churik** [comment]
### Environments
* Ethereum wallet used: MetaMask
* Browser: Chrome, Safari
* Operating System: macOS High Sierra 10.13.3

### Tested functionality
* adding new repo;
* renaming repo > repo name was changed on bounties before and after renaming;

**Pull request merged**
