### PR TITLE
Update web3j and solc versions

### PR DESCRIPTION
**Pull request by siphiuel**
This updates web3j version in `project.clj`. References in README have also been updated.

Obsolete unused fn removed (it caused problems during compilation due to unneeded last parameter).

Tested with latest web3j and Solidity compiler.

### CODE REVIEW

**Comment by churik** [comment]
Cannot be built (log from: https://jenkins.status.im/job/status-openbounty/job/status-openbounty-app/view/change-requests/job/PR-345/)
`[0m[91mjava.lang.ClassNotFoundException: org.web3j.protocol.core.methods.request.RawTransaction, compiling:(core.clj:1:1)
[0m[91mException in thread "main" [0m[91mjava.lang.ClassNotFoundException: org.web3j.protocol.core.methods.request.RawTransaction, compiling:(core.clj:1:1)
[0m[91m	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
[0m[91m	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
[0m[91m	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
[0m[91m	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
[0m[91m	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
[0m[91m	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
[0m[91m	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
[0m[91m	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:1789)
[0m[91m	at commiteth.scheduler$loading__5569__auto____5859.invoke(scheduler.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
[0m[91m	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)[0m[91m
[0m[91m	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)[0m[91m
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
[0m[91m	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)[0m[91m
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$compile$fn__5682.invoke(core.clj:5903)[0m[91m
	at clojure.core$compile.invokeStatic(core.clj:5903)
	at clojure.core$compile.invoke(core.clj:5895)
[0m[91m	at user$eval20$fn__29.invoke(form-init1201387604835371556.clj:1)
	at user$eval20.invokeStatic(form-init1201387604835371556.clj:1)
	at user$eval20.invoke(form-init1201387604835371556.clj:1)[0m[91m
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)[0m[91m
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)[0m[91m
	at clojure.main$init_opt.invokeStatic(main.clj:277)
[0m[91m	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
[0m[91m	at clojure.main$null_opt.invoke(main.clj:339)
[0m[91m	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
[0m[91m	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
[0m[91mCaused by: java.lang.ClassNotFoundException: org.web3j.protocol.core.methods.request.RawTransaction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[0m[91m	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)[0m[91m
[0m[91m	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2181)
[0m[91m	at commiteth.eth.core$loading__5569__auto____5861.invoke(core.clj:1)
[0m[91m	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 63 more
[0m[91mCompilation failed: Subprocess failed
[0mThe command '/bin/sh -c lein uberjar' returned a non-zero code: 1`

**Comment by siphiuel** [comment]
Fixed, in Web3j RawTransaction class used by offline signing code was moved to a different package, so imports had to be updated after merged with develop.

**Comment by siphiuel** [comment]
Broke again after merge with develop. Java contract files had to be regenerated and pushed to Git. Fixed.

**Comment by churik** [comment]
## 1. 404 when PR is deployed on testing env

Steps:
- build PR in Jenkins (deployed automatically)
- open https://testing.openbounty.status.im/

### Actual result:
404

### Expected result: 
200 OK

**Screen:** 


**Wallet**: MetaMask
**OS:**  Mac OS High Sierra
**Browser:** Chrome 64

**Comment by martinklepsch** [comment]
We can tackle this later if needed.

**Pull request closed without merging**
