### PR TITLE
Fix filter currency eth

### LINKED ISSUE #275: Filter by currency use 'AND' instead of 'OR'
### Description
As it turned out, most of users expect that filter by currency will use 'AND' instead of 'OR'

#### Expected behavior
'ETH' and 'SNT' enabled return all bounties with 'ETH', 'SNT' or with both of them

#### Actual behavior
'ETH' and 'SNT' enabled return only bounties with both 'ETH' and 'SNT'
ethsnt

### Reproduction

- Open Status
- tap on 'Currency'
- Tick 'ETH' and 'SNT' 

### Additional Information

* Browser: Chrome
* Operating System: Mac OS

### PR DESCRIPTION
**Pull request by pablodip**
Fixes #275 

Status: Finished.

Related: #279

### CODE REVIEW

**Comment by siphiuel** [comment]
Just noticed that `:balance-eth` bounty field is forcibly converted to string via `(update :balance-eth eth-decimal->str)` in `commiteth.routes.services/prettify-bounty-items`. So it arrives to CLJS as a string already. Maybe a better idea would be to convert them to string in the subscription that bounty page is consuming, not right away in `open-bounties`.

**Comment by pablodip** [comment]
@siphiuel How about doing that general data fixing in a bigger refactoring so that we ensure that this change doesn't affect any existent behaviour? :)

**Comment by siphiuel** [comment]
Yes, agree it might hurt down the road.

**Comment by churik** [comment]
### Environments:
* macOS HighSierra 10.13, Chrome  64
* macOS HighSierra 10.13, Safari  11
* macOS HighSierra 10.13, FireFox  58
### Tested functionality: 
verified that issue is not reproducible
### Regression: 
checked combination with 'Value', 'Owner' filter

**Pull request merged**
