### PR TITLE
[Fix #291] Fix command to run migrations

### LINKED ISSUE #291: Fix command to run migrations
### User Story

As a develop/devops I want to be able to run migrations with `lein run migrate`, as it is specified here: http://www.luminusweb.net/docs/migrations.html

### Description

This is important to separate running the app from running the migrations, that right now it is coupled, and everything the app is run, the migrations are run: https://github.com/status-im/open-bounty/blob/develop/src/clj/commiteth/db/core.clj#L29

Right now that command is broken with this output:

```
Exception in thread "main" java.lang.NullPointerException, compiling:(/private/var/folders/94/ynczyqvs09v8_7t8m21t5tt40000gn/T/form-init1764225723835109313.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at migratus.database$connect_STAR_.invokeStatic(database.clj:120)
	at migratus.database$connect_STAR_.invoke(database.clj:114)
	at migratus.database.Database.connect(database.clj:241)
	at migratus.core$run.invokeStatic(core.clj:24)
	at migratus.core$run.invoke(core.clj:21)
	at migratus.core$migrate.invokeStatic(core.clj:69)
	at migratus.core$migrate.invoke(core.clj:66)
	at luminus_migrations.core$migrate.invokeStatic(core.clj:73)
	at luminus_migrations.core$migrate.invoke(core.clj:52)
	at commiteth.core$_main.invokeStatic(core.clj:60)
	at commiteth.core$_main.doInvoke(core.clj:53)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:381)
	at user$eval30723.invokeStatic(form-init1764225723835109313.clj:1)
	at user$eval30723.invoke(form-init1764225723835109313.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

### PR DESCRIPTION
**Pull request by omartell**
Fixes #291
Status: Finished

## Summary

This fixes the code in main to run migrations. The issue was that the original code was using `:jdbc-database-url` vs `:database-url`. It now works for both migrations and rollbacks. I've also simplified the components started by mount as we only need to start env and not the db.

### CODE REVIEW

**Comment by pablodip** [comment]
@omartell Thank you for the PR! :)

Does the correction also fix the command that described the issue, `lein run migrate`? Not sure, since the PR just changes the core namespace. Just to confirm. :)

**Comment by omartell** [comment]
@pablodip thanks for the feedback. Yes, this fixes both `lein run migrate` and `lein run rollback`.

The app also run migrations right after starting up [here](https://github.com/status-im/open-bounty/blob/develop/src/clj/commiteth/db/core.clj#L29). I left that as it is as it's currently working and  I am assuming that's how you run migrations in production.

**Comment by martinklepsch** [comment]
@omartell awesome, good stuff 👍 

Sorry for the trouble but can you rebase against `develop` maybe?

**Comment by omartell** [comment]
@martinklepsch sure, done

**Comment by pablodip** [comment]
@omartell Thanks for the clarification!

> The app also run migrations right after starting up here. I left that as it is as it's currently working and I am assuming that's how you run migrations in production.

Yes, that is indeed something that we need to remove, but when we change our servers (we're on it), so that it doesn't affect to the current deployment system.

@martinklepsch We don't require rebasing, so asking for merging that is simpler should be enough.

**Comment by pablodip** [comment]
@omartell 

I am getting this error when running `lein run migrate` in an empty database:

`Exception in thread "main" org.postgresql.util.PSQLException: ERROR: cannot drop columns from view`.

When running the migrations that you mentioned (https://github.com/status-im/open-bounty/blob/develop/src/clj/commiteth/db/core.clj#L29), they work well.

Any ideas?

**Comment by omartell** [comment]
@pablodip I just dropped the db using `dropdb commiteth`, recreated it with `createdb commiteth`, then ran `lein run migrate` and it worked for me.

**Comment by pablodip** [comment]
@omartell It might be me then. @siphiuel @martinklepsch Could you please run it and confirm that it works for you with an empty database?

**Comment by siphiuel** [comment]
@pablodip @omartell  Just tried, `lein run migrate` worked without any issues.

**Comment by martinklepsch** [comment]
I'm running the following to test this:
```
dropdb commiteth
createdb commiteth
lein run migrate
```

and get this:
```
ERROR:  relation "schema_migrations" does not exist at character 15
STATEMENT:  SELECT 1 FROM schema_migrations
WARNING:  there is already a transaction in progress
```
Could this be because migrations are also ran when a namespace is loaded?

**Comment by omartell** [comment]
@martinklepsch migrations are also ran when running mount/start, not when the ns is loaded I think. Perhaps you have another process connecting to the DB and trying to run migrations?

**Comment by martinklepsch** [comment]
@omartell yeah, just looked at the code and agree. 

Have you tried the three commands I provided and can not reproduce the issue? 
I can reproduce even after killing all `java` processes beforehand.

**Comment by omartell** [comment]
Yes, have just ran the commands again and getting no error. I am using Postgres 9.6.5.

**Comment by martinklepsch** [comment]
Alright, maybe that's fine for now then. :+1:

**Pull request merged**
