### PR TITLE
Derive state of bounty from owner-bounties map

### LINKED ISSUE #300: Derive bounty state from database
In order to render a list of bounties on the dashboard of people managing bounties it would be useful to define some kind of data structure that completely describes the state of a bounty and can be used for rendering.

- Derive bounty state from database
- Simple Clojure data structure
- Potentially described using clojure.spec

##### EDITS

> Added some more context. @martinklepsch

### PR DESCRIPTION
**Pull request by martinklepsch**
Fixes #300

The `bounty-state` function here is my current understanding of the individual states and what's critical to advance from one state to another. 

For `status-im/status-react` this gives me the following stats:
```clj
{:merged 1, :paid 59, :opened 1, :funded 44}
```

- `:merged` https://github.com/status-im/status-react/issues/1267
- `:opened` https://github.com/status-im/status-react/issues/3116

##### QA NOTES

No UI changes.

### CODE REVIEW

**Comment by siphiuel** [comment]
I'd suggest to modify `bounty-state` slightly to accommodate more phase transitions. I've used doc/deployment_flow.md and doc/payout_flow.md to track these, e.g.:
```
  (cond
    ; After PR merge
    (:payout_receipt bounty) :paid-with-receipt
    (:payout_hash bounty) :paid
    (:confirm_hash bounty) :confirmed
    (:execute_hash bounty) :pending-maintainer-confirmation
    (not (:payout_address bounty)) :pending-contributor-address
    (:commit_sha bounty) :merged
    ; Before PR merge
    (< 1 (count (:claims bounty))) :multiple-claims
    (= 1 (count (:claims bounty))) :claimed
    (or (seq (:tokens bounty))
        (< 0 (:value_usd bounty))) :funded
    (:contract_address bounty) :contract-address-updated
    (:transaction_hash bounty) :contract-deployed)
```
Note that `:claim_count` is not available on `owner-bounties`, only on `open-bounties`. So we use `:claims` here.

**Comment by martinklepsch** [comment]
@siphiuel thanks for the review, good points. `:commit_sha` and `:claims` don’t seem to be part of `owner-bounties` though? Maybe I'll add a little utility that ensures that the used keys are present in the map provided.

**Comment by siphiuel** [comment]
`:commit_sha` - yes, it's not, missed it.

`:claims` should be there, as they are inserted by `commiteth.routes.services/user-bounties`.

**Comment by siphiuel** [comment]
And also `(:value_usd bounty)` is a string, not a number.

**Comment by martinklepsch** [comment]
> `:claims` should be there, as they are inserted by `commiteth.routes.services/user-bounties`.

I understand now. The `bounty-state` function was intended to work on the maps as they are returned by `owner-bounties`, not on the maps that are provided through the API. I'll reconsider that.

**Comment by martinklepsch** [comment]
Just pushed some changes I had made before I left for vacation. Basically some minor refactoring of `user-bounties` as well as asserting that the expected keys are present (could probably be done by spec in the future). 

In local testing I noticed that an exception (probably thrown by the assertion) was being serialized to Transit and sent to the client with a `200 OK` status code. This needs more investigation before we can merge this.

**Comment by churik** [comment]
### Environments
* Ethereum wallet used: MetaMask
* Browser: Chrome
* Operating System: macOS High Sierra 10.13.3

### Tested functionality
* Creating new issue with bounty;
* Create several claims for bounty;
* Confirming bounty payments;
* Merging PR - closing issue;
* That claiming issue impossible when winner is already set

**Pull request merged**
