### PR TITLE
Add wiki docs to the repo

### LINKED ISSUE #286: Transition Wiki into doc/ directory
As discussed in standup. Reasons mostly being that wiki might get out of sync with state of repository.

### PR DESCRIPTION
**Pull request by siphiuel**
Fixes #286.

### CODE REVIEW

**Comment by martinklepsch** [comment]
unfortunately this needs a rebase :smirk:

**Comment by siphiuel** [comment]
Oh noes.

**Comment by martinklepsch** [comment]
Perhaps as part of this PR clear out what's currently in the wiki and add a TOC that links to the pages in `doc/` or a README containing a TOC

**Comment by pablodip** [comment]
How about an index with links from the top of README?

**Comment by siphiuel** [comment]
Added `doc/README.md`.

**Comment by martinklepsch** [comment]
:clap: excellent Vitaly! I updated the Wiki homepage to point to the documentation in `develop`: https://github.com/status-im/open-bounty/wiki

**Comment by siphiuel** [comment]
Thanks, I was removing old wiki pages at the same time:)

**Comment by pablodip** [comment]
@siphiuel Oh, I meant at the top of the main README, so that anyone having a look at the repo can easily find and read the index, probably the most important part.

**Comment by siphiuel** [comment]
Added a small PR: https://github.com/status-im/open-bounty/pull/293

**Pull request merged**
