### PR TITLE
[FIX #156] Add pagination to Bounties and Activities views

### LINKED ISSUE #156: Paging for "open bounties" and activity views
Currently, if there is a lot of data in the system, the views get very long vertically.

Implement client-side paging to UI on "open bounties" and activity views.

### PR DESCRIPTION
**Pull request by siphiuel**
This adds client-side pagination to Bounties and Activities views.

### CODE REVIEW

**Comment by tpatja** [comment]
Looks really good @siphiuel! I will take a closer look and test this tomorrow.

**Comment by tpatja** [comment]
Since we do not currently have an easy way to test PRs and the changes look good, I will merge this to `develop` and we can test together in the test env. Possible changes can be submitted via a new PR.

**Comment by siphiuel** [comment]
Thanks! I think it would be good to do server-side paging as well, what do you think?

**Comment by tpatja** [comment]
IMO server-side paging is something we should do, but is not that urgent. The data is gzipped json and transferred data size is not an issue for now. We can create another issue for that later.

**Comment by pablodip** [comment]
I think there are a couple UX things to improve:

* The cursor in the buttons should be a pointer.
* When moving to a different page the screen should probably be moved to the top of the list.

cc @denis-sharypin

**Comment by siphiuel** [comment]
I will implement these if no objections from @denis-sharypin .

**Comment by siphiuel** [comment]
https://github.com/status-im/open-bounty/pull/224

**Comment by pablodip** [comment]
A few more of UX details:

* The button of next and previous page should probably look disabled when the current page is the first and the last one respectively.
* When changing the tab from bounties to activity and viceversa the current page should probably be restarted, that is, always be 1, and right now it is maintained from previous state.
* The activity list should also probably show at the top the message "Showing X of X".
* The next and previous buttons in active state have the same style as the current page button, and it is a bit confusing, since the next and previous are active, and the current page isn't an active thing thing.
* It would probably help to have some style changes when hovering paging buttons.

cc @denis-sharypin

**Comment by pablodip** [comment]
Just created a new issue for those UX details so that we keep better track of them in an open issue instead of a closed pull request.

https://github.com/status-im/open-bounty/issues/226

**Pull request merged**
