### PR TITLE
[FIX #187] Fix issue with "Select address" appearing after refresh

### LINKED ISSUE #187: Metamask address is not updated automatically in Payment Details
### Description

*Type*: Bug

*Summary*: 
when you setup Metamask, unlock it with your browser, login to SOB and go "My payment details" you see new address from MetaMask, but it is not really updated UNTIL you click update manually.
For you it looks like new address, but in database old address remains.

#### Expected behavior
address is updated in database (new address from MetaMask is set)

#### Actual behavior
address is updated on SOB but remains old (or empty, if it is first time) in DB
Only after you click UPDATE on SOB > Payment Details, it will be updated in DB

### Reproduction

- Open SOB
- Log in with user who set address manually or with new user
- Connect MetaMask for first time
- Go to "Payment Details"

### PR DESCRIPTION
**Pull request by siphiuel**
Add :user-profile-loaded? event/sub in order to guarantee that user profile data are loaded prior to displaying profile page.

### CODE REVIEW

**Comment by pablodip** [comment]
Couldn't that be known by checking that there is nothing in the subscription `:user`, so that we don't need new state and its corresponding management?

**Comment by siphiuel** [comment]
`:user` state is initialized with login data right away by `:set-active-user`, and then it is replaced with data fetched from DB by `:load-user-profile`. Therefore I did not want on specific fields in 1(:user app-db)`, but have a separate subscription instead.

**Comment by pablodip** [comment]
Okay then!

**Comment by pablodip** [comment]
@siphiuel Could you please update and merge the branch for QA?

**Comment by siphiuel** [comment]
Done.

**Comment by churik** [comment]
Checked in Chrome, Safari, Firefox (mac OSx HighSierra)

**Comment by churik** [comment]
### Environments:
* macOS HighSierra 10.13, Chrome  64
* macOS HighSierra 10.13, FireFox  58
### Tested functionality: 
* 'Update' address is disabled when address is not set (with empty field)
* Test plan: https://ethstatus.testrail.net/index.php?/plans/view/109 
### Regression: 
tested combination with 'Disguise myself from the top hunters and activity lists.'

**Pull request merged**
